### PR TITLE
initial site

### PR DESCRIPTION
**Pull request by eufat**
this one should work

### CODE REVIEW

**Comment by eufat** [comment]
di data.js ada typo, tolong ganti 'var speaker' jadi 'var speakers'

**Comment by zufrizalyordan** [comment]
sekalian aja bro di update sendiri, jadi ga perlu kita rebase/merge lagi biar sekalian merge sama yang ini.

**Comment by eufat** [comment]
@zufrizalyordan nantikan `data.js` harus diganti juga bro, soalnya itu sejenis `.json` yg diganti setiap kali ada meetup baru. tapi sebenernya gak ngefek juga sih soalnya ane gak pake `'use strict'`.

**Comment by hengkiardo** [comment]
@eufat please use `'use strict'`, using `'use strict'` on your code it make your code its as coding standard for JS code. 
and also why we should do changes `speaker` to `speakers`, kenapa gak langsung aja lo yg ganti bro? jadi kita tinggal merge.

**Comment by eufat** [comment]
@aredo pas gue cek ulang code gue, gue ketemu typo itu tepat abis pull request. untung lagi gak pake `'use strict'`, hehehe. gue pake `'use strict'` kalo codingan gue udah kyk spaghetti bgt supaya gampang di trace bug nya

**Comment by hengkiardo** [comment]
@eufat its ok. thanks for your efforts and i have just refactor the landing page and changes the content. 
now its live on url http://nodeschool.io/jakarta/

**Pull request merged**
